# Verificando propriedades de um ndarray

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([2, 0, 6, 9, 3, 6, 5, 2, 0, 3])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[89, 90, 86, 21, 66],
       [83, 50, 92, 92,  5],
       [85,  1, 81,  8, 52],
       [18, 21, 28, 46, 86]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.56144395, 0.18841913, 0.94338955, 0.01185645, 0.43524962],
        [0.6367397 , 0.67080436, 0.85316624, 0.01615165, 0.30667705],
        [0.23732408, 0.30482615, 0.01953426, 0.68936038, 0.37693778],
        [0.47394039, 0.37967018, 0.67098553, 0.68652107, 0.56415627]],

       [[0.59733179, 0.84743261, 0.01428763, 0.91521109, 0.357857  ],
        [0.74436069, 0.13755789, 0.51493332, 0.01802023, 0.42314046],
        [0.99422923, 0.02473202, 0.26464503, 0.28393262, 0.64990865],
        [0.05351349, 0.94249783, 0.4159647 , 0.30982874, 0.73333825]],

       [[0.31645076, 0.45386482, 0.49002777, 0.25163315, 0.45266125],
        [0.29479762, 0.24870164, 0.4976387 , 0.13088312, 0.77437124],
        [0.66783006, 0.16690835, 0.80203233, 0.14180422, 0.30239631],
        [0.04072201, 0.38967563, 0.08893578, 0.12781556, 0.7126626 ]]])

### Verificando o formato e quantidade de dimensões de um array - shape e dim

In [ ]:
# A propriedade shape retorna o formato do array
a1D.shape

In [ ]:
a2D.shape

In [ ]:
a3D.shape

In [ ]:
# A propriedade ndim retorna o números de dimensões do array
a1D.ndim

In [ ]:
a2D.ndim

In [ ]:
a3D.ndim

### Verificando o tamanho das dimensões de um array - len

In [ ]:
len(a1D) # Retorna o tamanho da 1a dimensão (quantidade de colunas)

In [ ]:
len(a2D) # Retorna o tamanho da 1a dimensão (quantidade de linhas)

In [ ]:
len(a2D[0]) # Retorna o tamanho da 2a dimensão (quantidade de colunas)

In [ ]:
len(a3D) # Retorna o tamanho da 1a dimensão (quantidade de páginas)

In [ ]:
len(a3D[0]) # Retorna o tamanho da 2a dimensão (quantidade de linhas)

In [ ]:
len(a3D[0][0]) # Retorna o tamanho da 3a dimensão (quantidade de colunas)

### Verificando a quantidade de elementos de um array - size

In [ ]:
a1D.size

In [ ]:
a2D.size

In [ ]:
a3D.size

### Verificando o tipo dos elementos um array - dtype

In [ ]:
a1D.dtype

In [ ]:
a1D.dtype.name

In [ ]:
a2D.dtype

In [ ]:
a2D.dtype.name

In [ ]:
a3D.dtype

In [ ]:
a3D.dtype.name

In [1]:
import numpy as np

# Lista aninhada
lista_aninhada = [[1, 2, 3], [4, 5, 6]]

# nd array
array_nd = np.array([[1, 2, 3], [4, 5, 6]])

# Operação em lista aninhada (soma de 10 a cada elemento)
lista_resultado = [[elemento + 10 for elemento in sublista] for sublista in lista_aninhada]

# Operação em nd array (soma de 10 a cada elemento)
array_resultado = array_nd + 10




Resultado da lista aninhada:
[[11, 12, 13], [14, 15, 16]]

Resultado do nd array:
[[11 12 13]
 [14 15 16]]


In [8]:
%%time
print("Resultado da lista aninhada:")
print(lista_resultado)



Resultado da lista aninhada:
[[11, 12, 13], [14, 15, 16]]
CPU times: total: 0 ns
Wall time: 0 ns


In [9]:
%%time
print("\nResultado do nd array:")
print(array_resultado)


Resultado do nd array:
[[11 12 13]
 [14 15 16]]
CPU times: total: 0 ns
Wall time: 1e+03 µs
