# Indexação e fatiamento (slicing)

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([6, 1, 5, 1, 8, 8, 9, 2, 8, 0])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[27, 34, 96, 16, 90],
       [72, 15, 45, 51, 57],
       [30, 96, 26,  6,  7],
       [92, 65, 71,  7, 24]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.01106247, 0.82737354, 0.12217049, 0.31028837, 0.55471361],
        [0.57685765, 0.20354924, 0.23027484, 0.17214341, 0.68214124],
        [0.974001  , 0.26930486, 0.37232954, 0.95949974, 0.47854782],
        [0.71514751, 0.82397839, 0.27420441, 0.57050925, 0.74431586]],

       [[0.08938828, 0.56705323, 0.68894318, 0.19437954, 0.47143871],
        [0.6185172 , 0.60450885, 0.86439395, 0.53130314, 0.56014806],
        [0.27084245, 0.85193708, 0.28807562, 0.22580175, 0.35876965],
        [0.9606816 , 0.71757063, 0.94609998, 0.31279213, 0.13877131]],

       [[0.98891661, 0.78021625, 0.06013735, 0.6877636 , 0.29379255],
        [0.03547601, 0.56919755, 0.92206448, 0.16968123, 0.20129399],
        [0.50574247, 0.07611804, 0.10409377, 0.79709076, 0.1593051 ],
        [0.57727212, 0.5842577 , 0.29374115, 0.08585174, 0.55899016]]])

### Acessando elementos específicos

In [5]:
# Acessando elementos de um ndarray de 1 dimensão
a1D

array([6, 1, 5, 1, 8, 8, 9, 2, 8, 0])

In [6]:
# nome_do_array[índice]
a1D[0]

6

In [7]:
a1D[2]

5

In [8]:
a1D[-1]

0

In [9]:
indices = [3, 0, -1] # Definindo uma lista com os índices que se deseja acessar
a1D[indices]

array([1, 6, 0])

In [10]:
# Acessando elementos de um ndarray de 2 dimensões
a2D

array([[27, 34, 96, 16, 90],
       [72, 15, 45, 51, 57],
       [30, 96, 26,  6,  7],
       [92, 65, 71,  7, 24]])

In [11]:
# nome_da_matriz[linha][coluna]
a2D[1][2]

45

In [12]:
a2D[3][4]

24

In [14]:
indice_lin = [0, 1, 2, 3]
indice_col = [0, 1, 2, 3]

a2D[indice_lin, indice_col]

array([27, 15, 26,  7])

In [15]:
indice_lin = [0, 1, 2, 3]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([16, 45, 96, 92])

In [16]:
indice_lin = [3, 2, 1, 0]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([ 7, 26, 15, 27])

In [17]:
a2D[:,[0,1,2,0]] 

array([[27, 34, 96, 27],
       [72, 15, 45, 72],
       [30, 96, 26, 30],
       [92, 65, 71, 92]])

In [18]:
a2D[:,[0,1,2,0]][[1, 0, 1, 0]]

array([[72, 15, 45, 72],
       [27, 34, 96, 27],
       [72, 15, 45, 72],
       [27, 34, 96, 27]])

In [19]:
a2D

array([[27, 34, 96, 16, 90],
       [72, 15, 45, 51, 57],
       [30, 96, 26,  6,  7],
       [92, 65, 71,  7, 24]])

In [20]:
a2D[[1, 0, 1, 0]][:,[0,1,2,0]] 

array([[72, 15, 45, 72],
       [27, 34, 96, 27],
       [72, 15, 45, 72],
       [27, 34, 96, 27]])

In [21]:
# Acessando elementos de um ndarray de 3 dimensões
a3D

array([[[0.01106247, 0.82737354, 0.12217049, 0.31028837, 0.55471361],
        [0.57685765, 0.20354924, 0.23027484, 0.17214341, 0.68214124],
        [0.974001  , 0.26930486, 0.37232954, 0.95949974, 0.47854782],
        [0.71514751, 0.82397839, 0.27420441, 0.57050925, 0.74431586]],

       [[0.08938828, 0.56705323, 0.68894318, 0.19437954, 0.47143871],
        [0.6185172 , 0.60450885, 0.86439395, 0.53130314, 0.56014806],
        [0.27084245, 0.85193708, 0.28807562, 0.22580175, 0.35876965],
        [0.9606816 , 0.71757063, 0.94609998, 0.31279213, 0.13877131]],

       [[0.98891661, 0.78021625, 0.06013735, 0.6877636 , 0.29379255],
        [0.03547601, 0.56919755, 0.92206448, 0.16968123, 0.20129399],
        [0.50574247, 0.07611804, 0.10409377, 0.79709076, 0.1593051 ],
        [0.57727212, 0.5842577 , 0.29374115, 0.08585174, 0.55899016]]])

In [24]:
# nome_do_cubo[página][linha][coluna]
a3D[2][0][3]

0.6877635991485037

In [23]:
a3D[0][3][1]

0.8239783903427486

### Fatiamento (slicing)

In [25]:
# Array de 1 dimensão
a1D

array([6, 1, 5, 1, 8, 8, 9, 2, 8, 0])

In [26]:
a = a1D[1:5] # Índice 1 ao 4
a

array([1, 5, 1, 8])

In [27]:
b = a1D[0:6] # Índice 0 ao 5
b

array([6, 1, 5, 1, 8, 8])

In [28]:
c = a1D[:6] # Do início ao 5
c

array([6, 1, 5, 1, 8, 8])

In [29]:
d = a1D[::2] # Do início ao fim, com passo 2
d

array([6, 5, 8, 9, 8])

In [30]:
e = a1D[-1::-1] # Do final até o início
e

array([0, 8, 2, 9, 8, 8, 1, 5, 1, 6])

In [31]:
# Array de 2 dimensões
a2D

array([[27, 34, 96, 16, 90],
       [72, 15, 45, 51, 57],
       [30, 96, 26,  6,  7],
       [92, 65, 71,  7, 24]])

In [ ]:
linha0 = a2D[0] # Todos os elementos da linha 0 - outra forma seria: linha0 = a2D[0,:]
linha0

In [ ]:
linha1 = a2D[1,:] # Todos os elementos da linha 1
linha1

In [ ]:
linha2 = a2D[2,1:4] # Linha 2, colunas 1, 2 e 3
linha2

In [ ]:
linha3 = a2D[:][3] # a2D[:] retorna toda a matriz, então de toda a matriz queremos a linha 3 a2D[:][3]
linha3

In [ ]:
coluna2 = a2D[:,2] # De todas as linhas, selecionar a coluna 2
coluna2

In [ ]:
coluna3 = a2D[1:,3] # Da linha um até a última, selecionar a coluna 3
coluna3

In [ ]:
# Array de 3 dimensões
a3D

In [ ]:
# Acessando a página/face 1
face1 = a3D[1]
face1

In [ ]:
# Acessando uma parte da face1
subface1 = a3D[1,0:3, 1:4]
subface1

In [ ]:
linha2face0 = a3D[0,2] # outra forma: linha2face0 = a3D[0,2,:]
linha2face0

In [ ]:
a3D

In [ ]:
linha1todasfaces = a3D[:,1] # outra forma: linha1todasfaces = a3D[:,1,:]
linha1todasfaces

In [ ]:
coluna3todasfaces = a3D[:,:,3]
coluna3todasfaces

### Indexação com booleanos

In [ ]:
a2D = np.random.randint(1, 501, (10, 8)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

In [ ]:
a2D >= 250

In [ ]:
a2D[a2D >= 250]

In [ ]:
a2D.mean()

In [ ]:
a2D[a2D <= a2D.mean()]