# Pandas Series

O objeto Series do módulo Pandas pode ser visto como um vetor ou matriz rotulada de 1 dimensão.

Para mais informações sobre **Series** do Pandas clique [aqui](https://pandas.pydata.org/pandas-docs/stable/reference/series.html).

O código fonte do objeto Series está disponível no Github. Quem tiver curiosidade pode visualizar clicando [aqui](https://github.com/pandas-dev/pandas/blob/v0.24.2/pandas/core/series.py).

In [1]:
import pandas as pd
import numpy as np

### Criando Series a partir de listas

In [2]:
idades = [68, 23, 17, 39, 25, 58]
idades

[68, 23, 17, 39, 25, 58]

In [3]:
s = pd.Series(idades)
s

0    68
1    23
2    17
3    39
4    25
5    58
dtype: int64

In [4]:
# Como retornar a idade 39?
s[3]

39

In [5]:
s = pd.Series([68, 23, 17, 39, 25, 58])
s

0    68
1    23
2    17
3    39
4    25
5    58
dtype: int64

In [7]:
pessoas = ['Eni', 'Bia', 'Flávio', 'Carlos', 'Dedé', 'Abigail']

In [8]:
s1 = pd.Series(idades, pessoas)
s1

Eni        68
Bia        23
Flávio     17
Carlos     39
Dedé       25
Abigail    58
dtype: int64

In [9]:
# Como retornar a idade 39, agora que a série está rotulada?
s1['Carlos']

39

In [10]:
s2 = pd.Series(index = pessoas, data = idades)
s2

Eni        68
Bia        23
Flávio     17
Carlos     39
Dedé       25
Abigail    58
dtype: int64

### Criando Series a partir de tuplas

In [11]:
# Minas Gerais teve seu nome digitado errado de forma intencional
nomes = ("Mnas Gerais", "Amazonas", "Maranhão", "Goiás", "Santa Catarina")
nomes

('Mnas Gerais', 'Amazonas', 'Maranhão', 'Goiás', 'Santa Catarina')

In [12]:
siglas = ("MG", "AM", "MA", "GO", "SC")
siglas

('MG', 'AM', 'MA', 'GO', 'SC')

In [13]:
estados = pd.Series(nomes, siglas)
estados

MG       Mnas Gerais
AM          Amazonas
MA          Maranhão
GO             Goiás
SC    Santa Catarina
dtype: object

In [14]:
estados["MG"] = "Minas Gerais"
estados

MG      Minas Gerais
AM          Amazonas
MA          Maranhão
GO             Goiás
SC    Santa Catarina
dtype: object

### Criando Series a partir de arrays NumPy

In [15]:
precos = np.array([25, 22, 18.5, 4.75, 3, 4.5, 2.3])
precos

array([25.  , 22.  , 18.5 ,  4.75,  3.  ,  4.5 ,  2.3 ])

In [16]:
type(precos)

numpy.ndarray

In [18]:
lanches = np.array(['X-tudo', 'X-Bacon', 'Bauru', 'Misto-quente', 'Pão-de-queijo', 'Coxinha', 'Pastel'])
lanches

array(['X-tudo', 'X-Bacon', 'Bauru', 'Misto-quente', 'Pão-de-queijo',
       'Coxinha', 'Pastel'], dtype='<U13')

In [19]:
s3 = pd.Series(precos)
s3

0    25.00
1    22.00
2    18.50
3     4.75
4     3.00
5     4.50
6     2.30
dtype: float64

In [20]:
cardapio = pd.Series(precos, lanches)
cardapio

X-tudo           25.00
X-Bacon          22.00
Bauru            18.50
Misto-quente      4.75
Pão-de-queijo     3.00
Coxinha           4.50
Pastel            2.30
dtype: float64

### Criando Series a partir de dicionários

In [21]:
dic_estados = {"MG": "Minas Gerais", "CE": "Ceará", "MT": "Mato Grosso", "RR": "Roraima"}
serie_estados = pd.Series(dic_estados)
serie_estados

MG    Minas Gerais
CE           Ceará
MT     Mato Grosso
RR         Roraima
dtype: object

In [22]:
dic_estados2 = {"MG": {"Estado":"Minas Gerais", "Capital":"Belo Horizonte", "População (2014)":20777672}, 
               "CE": {"Estado":"Ceará", "Capital":"Fortaleza", "População (2014)":8867448},
               "MT": {"Estado":"Mato Grosso", "Capital":"Cuiabá", "População (2014)":3236578},
               "RR": {"Estado":"Roraima", "Capital":"Boa Vista", "População (2014)":500826},}
serie_estados2 = pd.Series(dic_estados2)
serie_estados2

MG    {'Estado': 'Minas Gerais', 'Capital': 'Belo Ho...
CE    {'Estado': 'Ceará', 'Capital': 'Fortaleza', 'P...
MT    {'Estado': 'Mato Grosso', 'Capital': 'Cuiabá',...
RR    {'Estado': 'Roraima', 'Capital': 'Boa Vista', ...
dtype: object

In [23]:
serie_estados2["MT"]

{'Estado': 'Mato Grosso', 'Capital': 'Cuiabá', 'População (2014)': 3236578}

In [26]:
serie_estados2["RR"]["Capital"]

'Boa Vista'

### Criando Series a partir de arquivos .csv

In [25]:
# O arquivo idades.csv contém as idades de 100 pessoas (apenas 1 coluna)
idadescsv = pd.read_csv("idades.csv")
idadescsv.head() # mostra as primeiras linhas de uma Series ou DataFrame

Idades
0      55
1      45
2      74
3      18
4      21

In [27]:
# É possível acessar o índice 3?
idadescsv[3]

KeyError: 3

In [28]:
type(idadescsv)

pandas.core.frame.DataFrame

In [29]:
# Forma correta de acessar, mas vamos estudar o objeto DataFrame em outra aula
idadescsv['Idades'][3]

18

In [32]:
# Passando o argumento squeeze = True (por default squeeze = False)
# Quando squeeze = True, se os dados estiverem em apenas 1 dimensão, é então retornado uma Series
idadescsv = pd.read_csv("idades.csv").squeeze("columns")
idadescsv.head()

0    55
1    45
2    74
3    18
4    21
Name: Idades, dtype: int64

In [33]:
idadescsv[3]

18

In [34]:
type(idadescsv)

pandas.core.series.Series

In [36]:
# O arquivo idades2.csv contém o nomes e idade de 100 pessoas. A coluna nome será usada como índice.
idadescsv2 = pd.read_csv("idades2.csv").squeeze("columns")
idadescsv2.head()

Nome  Idade
0       Agatha     24
1        Alice     27
2       Alícia     18
3       Amanda     18
4  Ana Beatriz     44

In [37]:
type(idadescsv2)

pandas.core.frame.DataFrame

In [38]:
idadescsv3 = pd.read_csv("idades2.csv", index_col = 0).squeeze("columns")
idadescsv3.head()

Nome
Agatha         24
Alice          27
Alícia         18
Amanda         18
Ana Beatriz    44
Name: Idade, dtype: int64

In [39]:
idadescsv4 = pd.read_csv("idades2.csv", index_col = 1).squeeze("columns")
idadescsv4.head()

Idade
24         Agatha
27          Alice
18         Alícia
18         Amanda
44    Ana Beatriz
Name: Nome, dtype: object

### Criando Series a partir de planilhas do Excel

In [42]:
idadesxls = pd.read_excel("idades2.xlsx").squeeze("columns")
idadesxls.head()
# Abre a primeira planilha

0    55
1    45
2    74
3    18
4    21
Name: Idades, dtype: int64

In [43]:
idadesxls2 = pd.read_excel("idades2.xlsx", sheet_name="Planilha2")
idadesxls2.head()

Nome  Idade
0       Agatha     24
1        Alice     27
2       Alícia     18
3       Amanda     18
4  Ana Beatriz     44

In [44]:
type(idadesxls2)

pandas.core.frame.DataFrame

In [46]:
idadesxls3 = pd.read_excel("idades2.xlsx", sheet_name="Planilha2", index_col = 0).squeeze("columns")
idadesxls3.head()

Nome
Agatha         24
Alice          27
Alícia         18
Amanda         18
Ana Beatriz    44
Name: Idade, dtype: int64

In [47]:
type(idadesxls3)

pandas.core.series.Series

### Atributos do objeto Series

| Atributo | Descrição | Exemplo |
|:------------|:-------------------------------------------------------------------------|:--------------|
|[dtype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dtype.html) | Retorna o tipo dos dados armazenados em um objeto Series | `s.dtype`|
|[index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.index.html) | Retorna o índice (rótulos) de um objeto Series | `s.index`|
|[name](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.index.html) | Retorna o nome | `s.name`|
|[nbytes](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.nbytes.html) | Retorna o tamanho em bytes de um objeto Series | `s.nbytes`|
|[ndim](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.ndim.html) | Retorna o número de dimensões de um objeto Series | `s.ndim`|
|[shape](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.shape.html) | Retorna uma tupla com o formato de um objeto Series | `s.shape`|
|[size](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.size.html) | Retorna a quantidade de elementos de um objeto Series | `s.size`|
|[values](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.values.html) | Retorna os elementos de um objeto Series como um *ndarray*| `s.values`|

In [48]:
cardapio.dtype

dtype('float64')

In [49]:
cardapio.index

Index(['X-tudo', 'X-Bacon', 'Bauru', 'Misto-quente', 'Pão-de-queijo',
       'Coxinha', 'Pastel'],
      dtype='object')

In [50]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [51]:
cardapio.name = "Cardápio"

In [52]:
cardapio.name

'Cardápio'

In [53]:
cardapio.nbytes

56

In [54]:
cardapio.ndim

1

In [55]:
cardapio.shape

(7,)

In [56]:
cardapio.size

7

In [57]:
cardapio.values

array([25.  , 22.  , 18.5 ,  4.75,  3.  ,  4.5 ,  2.3 ])

### Métodos do objeto Series: indexação e iteração

| Método | Descrição | Exemplo |
|:------------|:-------------------------------------------------------------------------|:--------------|
|[at()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.at.html) | Acessa o elemento da chave passada por parâmetro | `s.iat["chave"]`|
|[iat()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.iat.html) | Acessa o elemento no índice passado por parâmetro | `s.iat(0)`|
|[get()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.get.html#pandas.Series.get) | Retorna um valor para a chave passada por parâmetro | `s.get(2)`|
|[loc()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.loc.html) | Acessa os elementos para as chaves passadas por parâmetro | `s.loc["chave1", "chave2"]`|
|[iloc()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.iloc.html) | Acesso via índice | `s.iloc[0] ou s.iloc[[1,3]]`|
|[keys()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.keys.html) | Retorna o índice (rótulos) de um objeto Series | `s.keys()`|

In [62]:
cardapio

X-tudo           25.50
X-Bacon          22.00
Bauru            18.50
Misto-quente      4.75
Pão-de-queijo     3.00
Coxinha           4.50
Pastel            2.30
Name: Cardápio, dtype: float64

In [59]:
cardapio.at["X-tudo"]

25.0

In [60]:
cardapio.iat[0]

25.0

In [61]:
cardapio.iat[0] = 25.5

In [63]:
cardapio.get(0)

C:\Users\Fabio\AppData\Local\Temp\ipykernel_13108\1228335089.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  cardapio.get(0)


25.5

In [64]:
cardapio.loc[["Bauru", "Pastel"]]

Bauru     18.5
Pastel     2.3
Name: Cardápio, dtype: float64

In [65]:
cardapio.iloc[[0,2,3]]

X-tudo          25.50
Bauru           18.50
Misto-quente     4.75
Name: Cardápio, dtype: float64

In [66]:
cardapio.keys()

Index(['X-tudo', 'X-Bacon', 'Bauru', 'Misto-quente', 'Pão-de-queijo',
       'Coxinha', 'Pastel'],
      dtype='object')

### Métodos do objetos Series: operações matemáticas e estatísticas

| Método | Descrição | Exemplo |
|:------------|:-------------------------------------------------------------------------|:--------------|
|[add()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.add.html) | Retorna a soma com outra Series ou escalar, elemento por elemento | `c = a.add(b, fill_value=0)`|
|[sub()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.sub.html) | Retorna a subtração com outra Series ou escalar, elemento por elemento | `c = a.sub(b, fill_value=3)`|
|[mul()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.mul.html) | Retorna a multiplicação com outra Series ou escalar, elemento por elemento | `c = a.mul(b, fill_value=1)`|
|[div()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.div.html) | Retorna a divisão com outra Series ou escalar, elemento por elemento | `c = a.div(b, fill_value=1)`|
|[floordiv()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.floordiv.html) | Retorna a divisão inteira com outra Series ou escalar, elemento por elemento | `c = a.floordiv(b, fill_value=1)`|
|[mod()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.mod.html) | Retorna o resto da divisão com outra Series ou escalar, elemento por elemento | `c = a.mod(b, fill_value=1)`|
|[pow()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.pow.html) | Retorna a potenciação com outra Series ou escalar, elemento por elemento | `c = a.pow(b, fill_value=1)`|
|[round()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.round.html) | Arredonda os valores de uma Series para uma quantidade determinada de casas decimais | `s = a.round(2)`|
|[lt()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.lt.html) | Retorna o resultado da comparação *menor que*, aplicada elemento por elemento, entre duas Series | `c = a.lt(b, fill_value=0)`|
|[gt()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.gt.html) | Retorna o resultado da comparação *maior que*, aplicada elemento por elemento, entre duas Series | `c = a.gt(b, fill_value=0)`|
|[le()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.le.html) | Retorna o resultado da comparação *menor ou igual*, aplicada elemento por elemento, entre duas Series | `c = a.le(b, fill_value=0)`|
|[ge()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.ge.html) | Retorna o resultado da comparação *maior ou igual*, aplicada elemento por elemento, entre duas Series | `c = a.ge(b, fill_value=0)`|
|[ne()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.ne.html) | Retorna o resultado da comparação *não igual a*, aplicada elemento por elemento, entre duas Series | `c = a.ne(b, fill_value=0)`|
|[eq()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.eq.html) | Retorna o resultado da comparação *igual a*, aplicada elemento por elemento, entre duas Series | `c = a.eq(b, fill_value=0)`|
|[product()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.product.html) | Retorna o produto entre todos os elementos de um objeto Series | `s.product()`|
|[sum()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.sum.html) | Retorna a soma entre todos os elementos de um objeto Series | `s.sum()`|
|[abs()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.abs.html) | Retorna valor absoluto de todos os elementos de um objeto Series | `s.abs()`|
|[mean()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.mean.html) | Retorna a média aritmética entre todos os elementos de um objeto Series | `s.mean()`|
|[count()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.count.html) | Retorna a quantidade de elementos não nulos | `s.count()`|
|[describe()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.describe.html) | Gera um relatório com diversas medidas estatísticas como média, percentis, etc...  | `s.describe()`|
|[max()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.max.html) | Retorna o maior valor | `s.max()`|
|[min()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.min.html) | Retorna o menor valor | `s.min()`|
|[median()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.median.html) | Retorna a mediana entre todos os elementos | `s.median()`|
|[nlargest()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.nlargest.html) | Retorna os *n* maiores elementos | `s.nlargest(3)`|
|[nsmallest()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.nsmallest.html) | Retorna os *n* menores elementos | `s.nsmallest(5)`|
|[quantile()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.quantile.html) | Retorna o valor de determinado quantil passado por parâmetro | `s.quantile(0.25)`|
|[std()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.std.html) | Retorna o desvio padrão | `s.std()`|
|[unique()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.unique.html) | Retorna  valores únicos | `s.unique()`|
|[nunique()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.nunique.html) | Retorna a quantidade de elementos únicos | `s.nunique()`|

### add(), sub(), mul(), div(), floordiv(), mod() e pow()

In [67]:
a = pd.Series([4, 8, 2, 5, 7])
b = pd.Series([1, 2, 3, 4, 5])
c = a.add(b)
print(" ",a.values)
print("+",b.values)
print("="*16)
print(c.values)

  [4 8 2 5 7]
+ [1 2 3 4 5]
[ 5 10  5  9 12]


In [68]:
a2 = a.add(3)
print(" ",a.values)
print("+",3)
print("="*16)
print(a2.values)

  [4 8 2 5 7]
+ 3
[ 7 11  5  8 10]


In [69]:
d = a.sub(b)
print(" ",a.values)
print("-",b.values)
print("="*16)
print(d.values)

  [4 8 2 5 7]
- [1 2 3 4 5]
[ 3  6 -1  1  2]


In [70]:
e = a.mul(b)
print(" ",a.values)
print("*",b.values)
print("="*16)
print(e.values)

  [4 8 2 5 7]
* [1 2 3 4 5]
[ 4 16  6 20 35]


In [71]:
f = a.div(b)
print(" ",a.values)
print("/",b.values)
print("="*16)
print(d.values)

  [4 8 2 5 7]
/ [1 2 3 4 5]
[ 3  6 -1  1  2]


In [72]:
g = a.floordiv(b)
print("  ",a.values)
print("//",b.values)
print("="*16)
print("  ",g.values)

   [4 8 2 5 7]
// [1 2 3 4 5]
   [4 4 0 1 1]


In [74]:
h = a.mod(b)
print(" ",a.values)
print("%",b.values)
print("="*16)
print(" ",h.values)

  [4 8 2 5 7]
% [1 2 3 4 5]
  [0 0 2 1 2]


In [75]:
i = a.pow(b)
print("  ",a.values)
print("**",b.values)
print("="*16)
print(" ",i.values)

   [4 8 2 5 7]
** [1 2 3 4 5]
  [    4    64     8   625 16807]


In [77]:
j = a.pow(2)
print("  ",a.values)
print("**",2)
print("="*16)
print(" ",j.values)

   [4 8 2 5 7]
** 2
  [16 64  4 25 49]


In [78]:
# usando o parâmetro fill_value
a = pd.Series([4, 3, 5, np.nan, None, 7], index=['a', 'b', 'c', 'd', 'e', 'f'])
a

a    4.0
b    3.0
c    5.0
d    NaN
e    NaN
f    7.0
dtype: float64

In [79]:
b = pd.Series([2, 5, np.nan, np.nan, 3, 6], index=['a', 'b', 'c', 'd', 'e', 'g'])
b

a    2.0
b    5.0
c    NaN
d    NaN
e    3.0
g    6.0
dtype: float64

In [80]:
k = a.div(b, fill_value = 1)
print(" ",a.values)
print("/",b.values)
print("="*16)
print(k.values)

  [ 4.  3.  5. nan nan  7.]
/ [ 2.  5. nan nan  3.  6.]
[2.         0.6        5.                nan 0.33333333 7.
 0.16666667]


### round()

In [81]:
a = pd.Series(np.random.randint(0, 100, 10)).pow(1/2)
a

0    9.899495
1    9.433981
2    9.591663
3    7.810250
4    9.110434
5    6.324555
6    2.645751
7    9.539392
8    4.898979
9    9.327379
dtype: float64

In [82]:
a = a.round(2)
a

0    9.90
1    9.43
2    9.59
3    7.81
4    9.11
5    6.32
6    2.65
7    9.54
8    4.90
9    9.33
dtype: float64

In [83]:
a = a.round(0)
a

0    10.0
1     9.0
2    10.0
3     8.0
4     9.0
5     6.0
6     3.0
7    10.0
8     5.0
9     9.0
dtype: float64

### lt(), gt(), le(), ge(), ne() e eq()

In [84]:
np.random.seed(51)
a = pd.Series(np.random.randint(0, 10, 5))
a

0    9
1    5
2    0
3    9
4    5
dtype: int32

In [85]:
b = pd.Series(np.random.randint(0, 10, 5))
b

0    0
1    5
2    4
3    9
4    5
dtype: int32

In [86]:
a.lt(b)

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [87]:
print(" ",a.values)
print("<",b.values)
print("="*32)
print(a.lt(b).values)

  [9 5 0 9 5]
< [0 5 4 9 5]
[False False  True False False]


In [88]:
print(" ",a.values)
print(">",b.values)
print("="*32)
print(a.gt(b).values)

  [9 5 0 9 5]
> [0 5 4 9 5]
[ True False False False False]


In [89]:
print("  ",a.values)
print("<=",b.values)
print("="*32)
print(a.le(b).values)

   [9 5 0 9 5]
<= [0 5 4 9 5]
[False  True  True  True  True]


In [90]:
print("  ",a.values)
print(">=",b.values)
print("="*32)
print(a.ge(b).values)

   [9 5 0 9 5]
>= [0 5 4 9 5]
[ True  True False  True  True]


In [91]:
print("  ",a.values)
print("!=",b.values)
print("="*32)
print(a.ne(b).values)

   [9 5 0 9 5]
!= [0 5 4 9 5]
[ True False  True False False]


In [92]:
print("  ",a.values)
print("==",b.values)
print("="*32)
print(a.eq(b).values)

   [9 5 0 9 5]
== [0 5 4 9 5]
[False  True False  True  True]


### sum(), product(), abs()

In [93]:
s

0    68
1    23
2    17
3    39
4    25
5    58
dtype: int64

In [94]:
s.sum()

230

In [95]:
s.product()

1503551400

In [96]:
posneg = pd.Series(np.arange(-6,6,2))
posneg

0   -6
1   -4
2   -2
3    0
4    2
5    4
dtype: int32

In [97]:
posneg.abs()

0    6
1    4
2    2
3    0
4    2
5    4
dtype: int32

### Métodos estatísticos

In [98]:
idadescsv3.describe()

count    100.000000
mean      35.570000
std       10.766817
min       18.000000
25%       26.750000
50%       34.000000
75%       45.250000
max       55.000000
Name: Idade, dtype: float64

In [99]:
idadescsv3.mean()

35.57

In [100]:
idadescsv3.std()

10.766816773510332

In [101]:
idadescsv3.median()

34.0

In [102]:
idadescsv3.min()

18

In [103]:
idadescsv3.max()

55

In [104]:
idadescsv3.quantile(0.25)

26.75

In [105]:
idadescsv3.quantile(.5)

34.0

In [106]:
idadescsv3.quantile(.75)

45.25

In [109]:
idadescsv3.nlargest(2)

Nome
Lucas        55
Valentina    54
Name: Idade, dtype: int64

In [110]:
idadescsv3.nsmallest(3)

Nome
Alícia      18
Amanda      18
Bernardo    18
Name: Idade, dtype: int64

In [112]:
idadescsv3.unique()

array([24, 27, 18, 44, 46, 49, 47, 41, 19, 25, 31, 42, 23, 39, 21, 33, 45,
       34, 43, 29, 36, 40, 32, 22, 48, 52, 51, 55, 53, 26, 54],
      dtype=int64)

In [113]:
# Usando np.sort para ordenar o array de elementos únicos
np.sort(idadescsv3.unique())

array([18, 19, 21, 22, 23, 24, 25, 26, 27, 29, 31, 32, 33, 34, 36, 39, 40,
       41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 52, 53, 54, 55],
      dtype=int64)

In [114]:
idadescsv3.nunique()

31

In [115]:
idadescsv3.count()

100

In [116]:
b = pd.Series([2, 5, np.nan, 0, 3, None, 6])
b.values

array([ 2.,  5., nan,  0.,  3., nan,  6.])

In [117]:
b.count()

5

### Métodos do objetos Series: manipulação e seleção

| Método | Descrição | Exemplo |
|:------------|:-------------------------------------------------------------------------|:--------------|
|[copy()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.copy.html#pandas.Series.copy) | Retorna uma cópia de um objetos Series | `s.copy()`|
|[append()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.append.html) | Concatena duas ou mais Series | `s = a.append(b)`|
|[replace()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.replace.html) | Substitui valor da Series por outro passado por parâmetro | `s = a.replace(-1, 0)`|
|[update()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.update.html) | Modifica uma série por valores de outra série passada por parâmetro | `a.update(b)`|
|[head()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.head.html) | Retorna as *n* primeiras linhas | `s.head(3)`|
|[tail()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.tail.html) | Retorna as *n* últimas linhas | `s.tail(4)`|
|[sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.sample.html) | Retorna uma amostra | `s.sample()`|
|[where()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.where.html) | Retorna uma Series onde valores para os quais a condição é **False** são substituídos por outro passado por parâmetro | `s.where(s <= 0, 5)`|
|[mask()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.mask.html) | Retorna uma Series onde valores para os quais a condição é **True** são substituídos por outro passado por parâmetro | `s.mask(s > 0, 5)`|

#### copy()

In [118]:
serie_estados2

MG    {'Estado': 'Minas Gerais', 'Capital': 'Belo Ho...
CE    {'Estado': 'Ceará', 'Capital': 'Fortaleza', 'P...
MT    {'Estado': 'Mato Grosso', 'Capital': 'Cuiabá',...
RR    {'Estado': 'Roraima', 'Capital': 'Boa Vista', ...
dtype: object

In [119]:
# Shallow copy
copia = serie_estados2.copy()
copia

MG    {'Estado': 'Minas Gerais', 'Capital': 'Belo Ho...
CE    {'Estado': 'Ceará', 'Capital': 'Fortaleza', 'P...
MT    {'Estado': 'Mato Grosso', 'Capital': 'Cuiabá',...
RR    {'Estado': 'Roraima', 'Capital': 'Boa Vista', ...
dtype: object

In [120]:
copia["MT"]["Capital"] = "CGB"
copia

MG    {'Estado': 'Minas Gerais', 'Capital': 'Belo Ho...
CE    {'Estado': 'Ceará', 'Capital': 'Fortaleza', 'P...
MT    {'Estado': 'Mato Grosso', 'Capital': 'CGB', 'P...
RR    {'Estado': 'Roraima', 'Capital': 'Boa Vista', ...
dtype: object

In [121]:
serie_estados2

MG    {'Estado': 'Minas Gerais', 'Capital': 'Belo Ho...
CE    {'Estado': 'Ceará', 'Capital': 'Fortaleza', 'P...
MT    {'Estado': 'Mato Grosso', 'Capital': 'CGB', 'P...
RR    {'Estado': 'Roraima', 'Capital': 'Boa Vista', ...
dtype: object

In [122]:
# Retornando ao valor original
serie_estados2["MT"]["Capital"] = "Cuiabá"
serie_estados2

MG    {'Estado': 'Minas Gerais', 'Capital': 'Belo Ho...
CE    {'Estado': 'Ceará', 'Capital': 'Fortaleza', 'P...
MT    {'Estado': 'Mato Grosso', 'Capital': 'Cuiabá',...
RR    {'Estado': 'Roraima', 'Capital': 'Boa Vista', ...
dtype: object

In [123]:
# Deep copy
import pickle
copia = pickle.loads(pickle.dumps(serie_estados2))

In [124]:
copia["MT"]["Capital"] = "CGB"
copia

MG    {'Estado': 'Minas Gerais', 'Capital': 'Belo Ho...
CE    {'Estado': 'Ceará', 'Capital': 'Fortaleza', 'P...
MT    {'Estado': 'Mato Grosso', 'Capital': 'CGB', 'P...
RR    {'Estado': 'Roraima', 'Capital': 'Boa Vista', ...
dtype: object

In [125]:
serie_estados2

MG    {'Estado': 'Minas Gerais', 'Capital': 'Belo Ho...
CE    {'Estado': 'Ceará', 'Capital': 'Fortaleza', 'P...
MT    {'Estado': 'Mato Grosso', 'Capital': 'Cuiabá',...
RR    {'Estado': 'Roraima', 'Capital': 'Boa Vista', ...
dtype: object

#### append()

In [129]:
a

0    9
1    5
2    0
3    9
4    5
dtype: int32

In [130]:
b

0    2.0
1    5.0
2    NaN
3    0.0
4    3.0
5    NaN
6    6.0
dtype: float64

In [132]:
ab = pd.concat([a, b])
ab

0    9.0
1    5.0
2    0.0
3    9.0
4    5.0
0    2.0
1    5.0
2    NaN
3    0.0
4    3.0
5    NaN
6    6.0
dtype: float64

In [135]:
ab = pd.concat([a, b], ignore_index=True)
ab

0     9.0
1     5.0
2     0.0
3     9.0
4     5.0
5     2.0
6     5.0
7     NaN
8     0.0
9     3.0
10    NaN
11    6.0
dtype: float64

#### replace()

In [136]:
c = ab.replace(0, 1)
c

0     9.0
1     5.0
2     1.0
3     9.0
4     5.0
5     2.0
6     5.0
7     NaN
8     1.0
9     3.0
10    NaN
11    6.0
dtype: float64


#### update()

In [137]:
d = pd.Series([4, 10, 11, 12], index=[9, 7, 10, 4])
d

9      4
7     10
10    11
4     12
dtype: int64

In [138]:
c.update(d)
c

0      9.0
1      5.0
2      1.0
3      9.0
4     12.0
5      2.0
6      5.0
7     10.0
8      1.0
9      4.0
10    11.0
11     6.0
dtype: float64

#### head()

In [139]:
idadescsv3.head() # Por default retornar as 5 primeiras linhas

Nome
Agatha         24
Alice          27
Alícia         18
Amanda         18
Ana Beatriz    44
Name: Idade, dtype: int64

In [140]:
idadescsv3.head(8)

Nome
Agatha         24
Alice          27
Alícia         18
Amanda         18
Ana Beatriz    44
Ana Clara      46
Ana Julia      49
Ana Luiza      47
Name: Idade, dtype: int64

#### tail()

In [141]:
idadescsv3.tail() # Por default retornar as 5 últimas linhas

Nome
Valentina    54
Vinicius     32
Vitor        41
Vitória      49
Yasmin       52
Name: Idade, dtype: int64

In [142]:
idadescsv3.tail(3)

Nome
Vitor      41
Vitória    49
Yasmin     52
Name: Idade, dtype: int64

#### sample()

In [145]:
idadescsv3.sample() # Por default retorna 1 linha de amostra

Nome
Rafael    49
Name: Idade, dtype: int64

In [144]:
idadescsv3.sample(5)

Nome
Maria Fernanda    18
Ian               48
Thiago            47
Ana Luiza         47
Agatha            24
Name: Idade, dtype: int64

#### where()

In [ ]:
c = a.append(b,ignore_index=True)
c

In [ ]:
d = c.where(c > 3, 10) # Troca valores por 10 se a condição for falsa
e = c.where(c <= 3, 0) # Troca valores por 0 se a condição for falsa
print("c.values", c.values)
print("d.values", d.values)
print("e.values", e.values)

#### mask()

In [ ]:
d = c.mask(c > 3, 10) # Troca valores por 10 se a condição for verdadeira
e = c.mask(c <= 3, 0) # Troca valores por 0 se a condição for verdadeira
print("c.values", c.values)
print("d.values", d.values)
print("e.values", e.values)

### Métodos do objetos Series: manipulação de dados ausentes

| Método | Descrição | Exemplo |
|:------------|:-------------------------------------------------------------------------|:--------------|
|[isna()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.isna.html) | Retorna quais valores estão ausentes | `s.isna()`|
|[notna()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.notna.html) | Retorna quais valores estão presentes | `s.notna()`|
|[dropna()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dropna.html) | Retorna uma nova Series com valores ausentes removidos | `s.dropna()`|
|[fillna()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.fillna.html) | Substitui valores ausentes por um valor ou usando um método de substituição  | `s.fillna(0)`|

In [ ]:
s = pd.Series([2, 5, np.nan, 0, 3, None, 6])
s.isna()

In [ ]:
s.notna()

In [ ]:
s1 = s.dropna()
s1

In [ ]:
s.dropna(inplace=True)
s

In [ ]:
s = pd.Series([2, 5, np.nan, 0, 3, None, 6])
s1 = s.fillna(-1)
print(s.values)
print(s1.values)

In [ ]:
# Preenche com o elemento posterior ao NaN
s2 = s.fillna(method='bfill')
print(s.values)
print(s2.values)

In [ ]:
# Preenche com o elemento anterior ao NaN
s3 = s.fillna(method='ffill')
print(s.values)
print(s3.values)

In [ ]:
s.fillna(-1, inplace=True)
s

### Métodos do objetos Series: ordenação

| Método | Descrição | Exemplo |
|:------------|:-------------------------------------------------------------------------|:--------------|
|[sort_values()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.sort_values.html) | Retorna uma Series ordenada pelos valores | `s.sort_values()`|
|[sort_index()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.sort_index.html) | Retorna uma Series ordenada pelos rótulos | `s.sort_index()`|

In [ ]:
idadescsv3.head()

In [ ]:
ordenado_id = idadescsv3.sort_values()
ordenado_id.head()

In [ ]:
idadescsv3.head()

In [ ]:
ordenado_nome = ordenado_id.sort_index()
ordenado_nome.head()

In [ ]:
ordenado_id.head()

### Métodos do objetos Series: manipulando strings

| Método | Descrição | Exemplo |
|:------------|:-------------------------------------------------------------------------|:--------------|
|[str.capitalize()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.capitalize.html) | Retorna uma Series com os Strings convertidos para a forma *capitalizada*: primeiro caractere maiúsculo e caracteres restantes em minúsculo | `s.str.capitalize()`|
|[str.lower()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.lower.html) | Retorna uma Series com os Strings convertidos  para letras minúsculas | `s.str.lower()`|
|[str.upper()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.upper.html) | Retorna uma Series com os Strings convertidos para letras maiúsculas | `s.str.upper() `|
|[str.title()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.title.html) | Retorna uma Series com os Strings convertidos para o formato de título: primeira letra de cada palavra convertida para maiúscula | `s.str.title() `|

In [ ]:
livros = pd.Series(["Introdução à programação com Python",
                    "Curso Intensivo de Python",
                    "Python para análise de dados"])
livros

In [ ]:
livros.str.lower()

In [ ]:
livros.str.upper()

In [ ]:
livros.str.capitalize()

In [ ]:
livros.str.title()

In [ ]:
livros

### Métodos do objetos Series: plotando gráficos

| Método | Descrição | Exemplo |
|:------------|:-------------------------------------------------------------------------|:--------------|
|[plot.area()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.plot.area.html) | Plota o gráfico de área | `s.plot.area()`|
|[plot.bar()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.plot.bar.html) | Plota o gráfico de barras | `s.plot.bar()`|
|[plot.box()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.plot.box.html) | Plota o Boxplot | `s.plot.box()`|
|[plot.hist()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.plot.hist.html) | Plota o histograma | `s.plot.hist()`|
|[plot.line()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.plot.line.html) | Plota o gráfico de linhas | `s.plot.line()`|

In [ ]:
# Gera uma série com 30 notas aleatórios entre 0 e 100
np.random.seed(50)
notas = pd.Series(np.random.randint(0,101, 30))
notas.head()

In [ ]:
notas.describe()

In [ ]:
#%matplotlib inline
notas.plot.hist()

In [ ]:
notas.plot.hist(101)

In [ ]:
np.sort(notas)

In [ ]:
notas.nunique()

In [ ]:
notas.plot.area()

In [ ]:
notas.plot.bar()

In [ ]:
notas.plot.box()

In [ ]:
print(notas.min(), notas.quantile(.25), notas.quantile(.5), notas.quantile(.75), notas.max())

In [ ]:
notas.plot.line()

In [ ]:
notas.hist()